namespace: community
name: rabbitmq
version: 1.0.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
  - community.rabbitmq (https://github.com/ansible-collections/rabbitmq/graphs/contributors)
description: null
license_file: COPYING
tags:
  - messaging
repository: https://github.com/ansible-collections/community.rabbitmq
documentation: https://github.com/ansible-collections/community.rabbitmq/README.md
homepage: https://github.com/ansible-collections/community.rabbitmq
issues: https://github.com/ansible-collections/community.rabbitmq/issues
